[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 115200
upload_port = COM5
upload_resetmethod = nodemcu

lib_deps =
  links2004/WebSockets@^2.5.0
  bblanchon/ArduinoJson@^7.3.1

build_flags =
  -DPIO_FRAMEWORK_ARDUINO_MMU_CACHE16_IRAM48_SECHEAP_SHARED
  -Iinclude


